---
sudo: false
language: python
dist: xenial
cache: pip

python:
  - '3.6'
  - '3.7'

env:
  matrix:
    - TOXENV=lint
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1

matrix:
  fast_finish: true

install:
  - travis_retry pip install --upgrade pip tox tox-venv tox-travis

script:
  - tox || travis_terminate 1

notifications:
  email: false

deploy:
  provider: pypi
  user: managedbyq
  password:
    secure: KknRgZiw3Y0+7Z2uWFBZkkah7Wtd3OCiFdkh7nq/+0aCGDxx7eyVJgs+yriqTVDobHbz4i9lrqYlZpgo8StKiPE0UKTlPt9HbD5xgjUoc7wZjzCnDREFukQPLegC7C8BRHAOuOj/IVUjazuEHcI9GbfVAdUI3mROupORqlUKa9tZ0z5g5Z7WjPtepga4CETi9PviZ+ZOmWV5KsJM+n0VvbS8Tq8ds1YRLetS8+kpYa2J0ON2hypb+vdC1SXvRoNJnGzhNnjHQlr1BUUa/JGHzC8Sy5LJbU3LK7njN5XPkvDx8A0/GFAMk60PACGaWF0lxV/K3aLMWPO/820A+3+mVgWHYFwDQ+UjOoVPB+Yh9i7AvYMTeL4XjVNxvvr1LSOs+BvKjjJsvOrc1uG3h412Sl/mQwIZ1UVj/sKc3N5gZNDQ+UwIcggVZ7O6rJnlkIQH50tTMnE8ZNyJY/dDBQVp4BflJfVA99cl7v4WuwVRIKJIIVh1cx31iKZUskV7WMCSKv3Tkg/lYunRfBTZ3y1GPZ1C+vspTxoZIatzOzu2mQvN2kaifCSJjuKHff92PzuZI+Sc++kneqpQgC0dzfAXWscatkGT66vr5OdtiTJQnd7TAiflQx+fDOJcZOIxVGcA33v0hG1ukBMcWzHMA3xVJ2i5myA/RTslbIVi7Ls0VMw=
  on:
    repo: managedbyq/mbq.apitools
    branch: master
    tags: true
    python: '3.6'
    # admittedly, this condition is a bit silly but we want the deploy to happen
    # on exactly one build, not all py36 builds, and looking for django 1.11 is
    # a cheap way to accomplish that.
    condition: $DJANGO = '1.11'
    distributions: sdist bdist_wheel
