---
sudo: false
language: python
dist: xenial
cache: pip

python:
  - '3.6'
  - '3.7'

env:
  matrix:
    - TOXENV=lint
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1

matrix:
  fast_finish: true

install:
  - travis_retry pip install --upgrade pip tox tox-venv tox-travis

script:
  - tox || travis_terminate 1

notifications:
  email: false

deploy:
  provider: pypi
  user: managedbyq
  password:
    secure: zNBqEyPTJRUnFqweqSr+9H11ZG7eZNme/AzcDvERv8dEhOxqNo4ODKj1tvz5IWlL5koEPrJt63BzpyUnPoJbOzsh5X/GTgbY/ovOZG13PxujgyiV/SFRtXNp+kFiGjWWmO6ADNQjc6j2eSG+86zMglhiq5NF9JfXueU1WGn3bWDbaeaO80Bf4QXfWyqQ2cVWMBQzzcNl2gH+mI2oe+fIDGqY94VXFZDsEk3WgK1gwvWDnhI770nzh6ws1nzEriuInymQNDhplvE0zGzZiPERru8obfYfvdhh0AZJqB9itRw34175tIrwhsodeidf2FN5U4lwuQW8hsJDEZzMrZAfHxKJBjbtGTq8+pHLuaXirCWAe5P7EGRKyqodUc2/N0MypPj7X1Bd5v+ck+PWNpTmJ0K9h1dozPSqCMYfjL53HILAcfOiSFQwd0UmZlc0b5uTjX+s4uhr23nyaOh3/ky0H90WLERfXb3ibrT+ar9osb9CBulmuYQlr20EATzA6UrdFSvkLwNi9nCZBWb0/5ULq6P+o63MVGWot45UZhA9AaoSzil+EESpzEWR3Z3gWpnI62cllNZHqI6o+VyCGEZNDIiwcgI51RxqK78LYTJmrj3BcwkKa3dNBv5Rec4M3rtwHecGlhOCFz2TrqbN4BX3ND5e4PZJFR/DDLFr/HAM/Q=
  on:
    repo: managedbyq/mbq.apitools
    branch: master
    tags: true
    python: '3.6'
    # admittedly, this condition is a bit silly but we want the deploy to happen
    # on exactly one build, not all py36 builds, and looking for django 1.11 is
    # a cheap way to accomplish that.
    condition: $DJANGO = '1.11'
    distributions: sdist bdist_wheel
